[package]
name = "research-platform-sh-problem"
version = "0.1.0"
authors = ["Masahiro Honma <hiratara@cpan.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
publicsuffix="1.5.4"
